### PR TITLE
Added a cmake build script and fixed errors when compiling with GCC

### PR DESCRIPTION
**Pull request by hhyyrylainen**
I added this library to a linux project of mine and thought I might as well contribute these fixes back.

Things I fixed (in addition to the cmake build script):

There were a lot of MatchResults that were constructed with falses
I had to replace those with nullptrs

There was also one unused value that I thought was probably meant to be
returned

And also there were illegal references taken, some of which I changed to
const references and some to plain values (iterators)

I also reordered a few initializations which were in the wrong order.

And I fixed the std::locale name on linux

### CODE REVIEW

**Comment by TechnikEmpire** [comment]
@hhyyrylainen Sweet, thanks. I'm curious though, I made a constructor for the `Selector::MatchResult` IIRC that takes a boolean argument, so returning `false` should have constructed a match result denoting no match. What effect does returning `nullptr` have? It's been a long time since my head was anywhere near this code.

**Comment by TechnikEmpire** [comment]
@hhyyrylainen  Nevermind, I can see that returning nullptr gives the appropriate result. I'm not sure what I was doing there, but you're right in your changes. Thanks again, I hope this was helpful. 😄

**Comment by TechnikEmpire** [comment]
@hhyyrylainen Added you to the AUTHORS file. Thanks again.

**Comment by hhyyrylainen** [comment]
@TechnikEmpire I only found one constructor for `MatchResult` : `MatchResult(const Node* result = nullptr);`
What might be happening is that visual studio lets you implicitly convert false to a pointer type, whereas GCC is more strict about this.

**Comment by TechnikEmpire** [comment]
@hhyyrylainen Yes I believe you're correct. Visual studio was letting me do something evil. Thanks for catching it. :)

**Pull request merged**
